version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/clean_webroot
      runas: root
  
  AfterInstall:
    - location: scripts/install_python3
      timeout: 300
      runas: root 
    - location: scripts/install_httpd
      timeout: 300
      runas: root 
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/status_apache
      timeout: 3600
      runas: root
