version: 0.0
os: linux

files:
  - source: ./src
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/clean_webroot.sh
      runas: root
  AfterInstall:
    - location: scripts/install_httpd
      timeout: 300
      runas: root 
  ApplicationStop:
    - location: scripts/stop_httpd.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: scripts/status_httpd.sh
      timeout: 3600
      runas: root
