version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/clean_webroot.sh
      runas: root
  
  AfterInstall:
    - location: scripts/install_httpd
      timeout: 300
      runas: root 
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/stop_httpd.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 3600
      runas: root
    - location: scripts/register_with_elb.sh
  ValidateService:
    - location: scripts/status_httpd.sh
      timeout: 3600
      runas: root
